version: '3.1'
services:
  API:
    image: 'pcr_backend'
    ports:
      - '8080:8080'
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/pcr_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  PostgreSQL:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pcr_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
