version: "3"
services:
  pgdb:
    image: pgdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: backend
    ports:
      - 7801:7801
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql