app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      #For running in docker, where PostgreSQL is the custom name of the image
      #jdbc-url: jdbc:postgresql://kevinmorales/pgdb:5432/postgres
      #For running locally with separate db
      jdbc-url: jdbc:postgresql://moxie.cs.oswego.edu:5432/postgres
      #jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: "postgresql"
      pool-size: 30

server:
  error:
    include-binding-errors: never
    include-stacktrace: on_trace_param
    whitelabel:
      enabled: false
    path: "/error"
