app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: "postgresql"
      pool-size: 30

server:
  error:
    include-binding-errors: never
    include-message: never
