app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      pool-size: 30

server:
  error:
    include-binding-errors: never
    include-stacktrace: on_trace_param
    whitelabel:
      enabled: false
  port: 7801
